"""empty message

Revision ID: 446c59b6f674
Revises: 9aee7730118c
Create Date: 2020-07-21 23:30:29.096800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446c59b6f674'
down_revision = '9aee7730118c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
